### ISSUE TITLE
Issue in Channel::send()

### ISSUE THREAD

**Issue by bbryndak** [nsumner/web-socket-networking#1]
In the file lib/networking/src/Server.cpp, the method send() of the Channel class seems to work by sending messages from the front of the writeBuffer queue, but on the line 142 the async_write function sends the message from the back of the writeBuffer.

Also, since the server is single-threaded, is there a need for the writeBuffer in the Channel? It looks like it worked fine with the messages being sent out of order.

**Comment by nsumner** [comment]
That does look like it should be fixed.

I've actually not run into a scenario where the chained processing is necessary, but some users have. It's possible that it is rare enough that even just buffering two events suffices, which would make the front and back the same after one is processed. Under more serious load, that may change.

**Comment by nsumner** [comment]
Updated.
